//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constants
    {
        public float alcoWait { get; set; }
        public Nullable<byte> alcoDoubleDiagnosis { get; set; }
        public Nullable<int> timeoutParamedicEdit { get; set; }
        public Nullable<int> notificationDelay { get; set; }
        public double alcoWarning { get; set; }
        public double alcoCritical { get; set; }
        public byte metal { get; set; }
        public byte guiConfig { get; set; }
        public long id { get; set; }
    }
}
