//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnosis()
        {
            this.VerificationQueue = new HashSet<VerificationQueue>();
            this.VerificationResult = new HashSet<VerificationResult>();
        }
    
        public System.Guid id { get; set; }
        public long personID { get; set; }
        public long terminalID { get; set; }
        public Nullable<long> paramedicID { get; set; }
        public Nullable<double> alcoResult { get; set; }
        public System.DateTime diagnosisDateTime { get; set; }
        public string startPhotoPath { get; set; }
        public string videoPath { get; set; }
        public Nullable<byte> paramedicVisit { get; set; }
        public Nullable<double> paramedicResult { get; set; }
        public string diagnosisParamedic { get; set; }
        public string status { get; set; }
        public byte direction { get; set; }
        public Nullable<byte> verification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerificationQueue> VerificationQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerificationResult> VerificationResult { get; set; }
        public virtual UserRoles UserRoles { get; set; }
        public virtual Users Users { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
