//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyService.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class localdb4Entities : DbContext
    {
        public localdb4Entities()
            : base("name=localdb4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Constants> Constants { get; set; }
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<FaceDescriptor> FaceDescriptor { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Kpp> Kpp { get; set; }
        public virtual DbSet<MailService> MailService { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Struct> Struct { get; set; }
        public virtual DbSet<Subscriptions> Subscriptions { get; set; }
        public virtual DbSet<Terminal> Terminal { get; set; }
        public virtual DbSet<TerminalCondition> TerminalCondition { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VerificationQueue> VerificationQueue { get; set; }
        public virtual DbSet<VerificationResult> VerificationResult { get; set; }
        public virtual DbSet<WorkCheck> WorkCheck { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
    }
}
