//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public long id { get; set; }
        public long terminalID { get; set; }
        public Nullable<System.TimeSpan> inStart { get; set; }
        public Nullable<System.TimeSpan> inStop { get; set; }
        public Nullable<System.TimeSpan> outStart { get; set; }
        public Nullable<System.TimeSpan> outStop { get; set; }
        public Nullable<System.TimeSpan> blockStart { get; set; }
        public Nullable<System.TimeSpan> blockStop { get; set; }
    
        public virtual Terminal Terminal { get; set; }
    }
}
