//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalCondition
    {
        public long id { get; set; }
        public long terminalID { get; set; }
        public System.DateTime timeUpdated { get; set; }
        public float temperature { get; set; }
        public Nullable<byte> rfidReaderStatus { get; set; }
        public Nullable<byte> alcoInStatus { get; set; }
        public Nullable<byte> alcoOutStatus { get; set; }
        public Nullable<byte> metalStatus { get; set; }
        public Nullable<byte> webcamInStatus { get; set; }
        public Nullable<byte> webcamOutStatus { get; set; }
        public Nullable<byte> turnstileStatus { get; set; }
    
        public virtual Terminal Terminal { get; set; }
    }
}
