//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Diagnosis = new HashSet<Diagnosis>();
            this.UserRoles = new HashSet<UserRoles>();
            this.VerificationResult = new HashSet<VerificationResult>();
            this.VerificationResult1 = new HashSet<VerificationResult>();
        }
    
        public long id { get; set; }
        public string identificationCardCode { get; set; }
        public string personNumber { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string patronymicName { get; set; }
        public string photoPath { get; set; }
        public string jobPosition { get; set; }
        public string department { get; set; }
        public string passID { get; set; }
        public Nullable<byte> archived { get; set; }
        public Nullable<byte> placeControl { get; set; }
        public Nullable<long> structCode { get; set; }
        public Nullable<long> firm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosis> Diagnosis { get; set; }
        public virtual FaceDescriptor FaceDescriptor { get; set; }
        public virtual Firm Firm1 { get; set; }
        public virtual Struct Struct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoles> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerificationResult> VerificationResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerificationResult> VerificationResult1 { get; set; }
    }
}
