//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificationResult
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> diagnosisId { get; set; }
        public Nullable<long> personId { get; set; }
        public Nullable<long> expectedId { get; set; }
        public Nullable<float> probability { get; set; }
        public Nullable<float> criteria { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
