//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace facerecognition {

public class ResultVerify : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ResultVerify(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ResultVerify obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ResultVerify() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          facerecognitionPINVOKE.delete_ResultVerify(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ResultVerify() : this(facerecognitionPINVOKE.new_ResultVerify(), true) {
  }

  public bool isVerify {
    set {
      facerecognitionPINVOKE.ResultVerify_isVerify_set(swigCPtr, value);
    } 
    get {
      bool ret = facerecognitionPINVOKE.ResultVerify_isVerify_get(swigCPtr);
      return ret;
    } 
  }

  public ListString data {
    set {
      facerecognitionPINVOKE.ResultVerify_data_set(swigCPtr, ListString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = facerecognitionPINVOKE.ResultVerify_data_get(swigCPtr);
      ListString ret = (cPtr == global::System.IntPtr.Zero) ? null : new ListString(cPtr, false);
      return ret;
    } 
  }

  public string data_t {
    set {
      facerecognitionPINVOKE.ResultVerify_data_t_set(swigCPtr, value);
      if (facerecognitionPINVOKE.SWIGPendingException.Pending) throw facerecognitionPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = facerecognitionPINVOKE.ResultVerify_data_t_get(swigCPtr);
      if (facerecognitionPINVOKE.SWIGPendingException.Pending) throw facerecognitionPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int num_face {
    set {
      facerecognitionPINVOKE.ResultVerify_num_face_set(swigCPtr, value);
    } 
    get {
      int ret = facerecognitionPINVOKE.ResultVerify_num_face_get(swigCPtr);
      return ret;
    } 
  }

  public double level {
    set {
      facerecognitionPINVOKE.ResultVerify_level_set(swigCPtr, value);
    } 
    get {
      double ret = facerecognitionPINVOKE.ResultVerify_level_get(swigCPtr);
      return ret;
    } 
  }

}

}
